import math

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

ASPECT_RATIO = WINDOW_WIDTH / WINDOW_HEIGHT
FOV = math.pi / 3
NEAR_Z = 0.1
FAR_Z = 2000.0

PLAYER_SPEED = 5.0
PLAYER_ROTATE_SPEED = 2.0

CHUNK_SIZE = 32
HALF_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOLUME = CHUNK_SIZE * CHUNK_AREA

WORLD_WIDTH, WORLD_DEPTH = 10, 10
WORLD_HEIGHT = 3
WORLD_AREA = WORLD_WIDTH * WORLD_DEPTH
WORLD_VOLUME = WORLD_AREA * WORLD_HEIGHT
